### ISSUE TITLE
FFTW needed?

### ISSUE THREAD

**Issue by michael-petersen** [EXP-code/EXP#53]
A test compilation where FFTW was accidentally not included seemed to suggest that `cmake` still needed `FFTW_INCLUDE_DIRS`. To be investigated...

**Comment by The9Cat** [comment]
FFTW is used by `TransformFFT` for the DFT computations in pyEXP and  by `gensph`.  We could switch off DFT computations  and not compile `gensph` if `fftw` is *not found*.  But I'm currently thinking that it might be better to require FFTW.

Thoughts on this?

**Comment by michael-petersen** [comment]
This is addressed by #90. We haven't had any complaints about requiring FFTW, so I think this is an easy fix.
